Repository prgrms-web-devcourse-final-project/WEB5_6_HaeDokCoding_FE, pull requests merged in 2025-09, with the labels that each got.

#33 docs/shared 폴더 생성
  src/app/design-system/page.tsx
  src/app/layout.tsx
  src/shared/@store/store.ts
  src/shared/@types/index.ts
  src/shared/assets/icons/bell_24.svg
  src/shared/assets/icons/close_20.svg
  src/shared/assets/icons/comment_28.svg
  src/shared/assets/icons/edit_28.svg
  src/shared/assets/icons/github_32.svg
  src/shared/assets/icons/help_24.svg
  src/shared/assets/icons/imageBox_24.svg
  src/shared/assets/icons/imageBox_fill_24.svg
  src/shared/assets/icons/keep_36.svg
  src/shared/assets/icons/keep_active_36.svg
  src/shared/assets/icons/like_28.svg
  src/shared/assets/icons/like_active_28.svg
  src/shared/assets/icons/link_36.svg
  src/shared/assets/icons/search_32.svg
  src/shared/assets/icons/selectDown_24.svg
  src/shared/assets/icons/send_36.svg
  src/shared/assets/icons/share_24.svg
  src/shared/assets/icons/singout_24.svg
  src/shared/assets/icons/tag_24.svg
  src/shared/assets/icons/user_24.svg
  src/shared/assets/images/index.ts
  src/shared/components/Button.tsx
  src/shared/components/index.tsx
  src/shared/hook/index.ts
  src/shared/lib/index.ts
  src/shared/styles/_base.css
  src/shared/styles/_components.css
  src/shared/styles/_theme.css
  src/shared/styles/_utilities.css
  src/shared/styles/global.css
  src/shared/utills/debounce.ts
  src/shared/utills/scrollToTop.ts
  src/shared/utills/test.ts
  src/shared/utills/throttle.ts
  src/shared/utills/tw.ts
Labels: chore

#35 [feat] 공통 팝업 구현#7
  next.config.ts
  src/app/design-system/page.tsx
  src/app/layout.tsx
  src/shared/assets/icons/close_20.svg
  src/shared/assets/icons/close_32.svg
  src/shared/components/ModalPop/ConfirmPop.tsx
  src/shared/components/ModalPop/ModalLayout.tsx
  src/shared/components/ModalPop/Portal.tsx
  src/shared/styles/_base.css
Labels: design, feat

#36 [feat] toast 구현
  package-lock.json
  package.json
  src/app/design-system/page.tsx
  src/app/layout.tsx
  src/shared/assets/icons/close_20.svg
  src/shared/assets/icons/error_toast_32.svg
  src/shared/assets/icons/info_toast_32.svg
  src/shared/assets/icons/success_toast_32.svg
  src/shared/components/ModalPop/ConfirmPop.tsx
  src/shared/components/ModalPop/ModalLayout.tsx
  src/shared/components/button/Button.tsx
  src/shared/components/toast/CustomToast.tsx
  src/shared/components/toast/CustomToastUtils.tsx
  src/shared/styles/_theme.css
  src/shared/styles/global.css
Labels: feat

#52 Feat/spinner#5
  package-lock.json
  package.json
  src/app/community/page.tsx
  src/app/design-system/page.tsx
  src/shared/assets/lottie/loading.json
  src/shared/components/header/DropdownMenu.tsx
  src/shared/components/spinner/Spinner.tsx
Labels: design

#56 Style/community#18
  src/app/community/page.tsx
  src/shared/assets/images/prepost_img.webp
  src/shared/components/InputBox/SelectBox.tsx
  src/shared/components/community/CommunityFilter.tsx
  src/shared/components/community/CommunityHeader.tsx
  src/shared/components/community/CommunityTab.tsx
  src/shared/components/community/PostCard.tsx
  src/shared/components/community/PostLabel.tsx
  src/shared/components/community/WriteBtn.tsx
  src/shared/components/header/DropdownMenu.tsx
  src/shared/styles/global.css
Labels: design

#66 Style/community#18
  package-lock.json
  package.json
  src/app/community/page.tsx
  src/domains/community/detail/DetailContent.tsx
  src/domains/community/main/CommunityFilter.tsx
  src/domains/community/main/CommunityHeader.tsx
  src/domains/community/main/CommunityTab.tsx
  src/domains/community/main/PostCard.tsx
  src/domains/community/main/PostInfo.tsx
  src/domains/community/main/WriteBtn.tsx
  src/shared/components/header/DropdownMenu.tsx
  src/shared/components/header/Header.tsx
Labels: refactor

#69 [docs] 폴더명 카멜케이스 -> 케밥케이스로 변경
  src/app/community/[id]/page.tsx
  src/app/community/page.tsx
  src/app/design-system/page.tsx
  src/app/layout.tsx
  src/app/recipe/[id]/page.tsx
  src/app/recipe/page.tsx
  src/domains/community/CommunityFilter.tsx
  src/domains/community/CommunityHeader.tsx
  src/domains/community/PostCard.tsx
  src/domains/community/detail/DetailHeader.tsx
  src/domains/community/detail/comment/DetailComment.tsx
  src/domains/community/detail/tab/DetailTabDesktop.tsx
  src/domains/community/detail/tab/DetailTabMobile.tsx
  src/domains/community/main/CommunityFilter.tsx
  src/domains/community/main/CommunityHeader.tsx
  src/domains/community/main/PostCard.tsx
  src/domains/login/components/LogoutConfirm.tsx
  src/domains/login/components/WelcomeModal.tsx
  src/domains/recipe/CocktailCard.tsx
  src/domains/recipe/components/main/Accordion.tsx
  src/domains/recipe/details/DetailItem.tsx
  src/domains/recipe/details/DetailsHeader.tsx
  src/domains/recommend/components/ChatCocktailCard.tsx
  src/domains/shared/components/keep/Keep.tsx
  src/domains/shared/components/label/Label.tsx
  src/domains/shared/components/page-header/PageHeader.tsx
  src/domains/shared/components/select-box/SelectBox.tsx
  src/domains/shared/components/share/Share.tsx
  src/domains/shared/components/star-bg/StarBg.tsx
  src/shared/components/Input-box/Input.tsx
  src/shared/components/modal-pop/ConfirmModal.tsx
  src/shared/components/modal-pop/ModalLayout.tsx
  src/shared/components/modal-pop/Portal.tsx
  src/shared/components/scroll-top/ScrollTopBtn.tsx
  src/shared/components/scroll-top/ScrollTopBtnWrapper.tsx
Labels: chore

#73 Feat/칵테일 추천리스트t#27
  src/domains/recipe/CocktailCard.tsx
  src/domains/recipe/CocktailList.tsx
  src/domains/recipe/details/DetailList.tsx
  src/domains/recipe/details/DetailMain.tsx
  src/domains/recipe/details/DetailRecommendList.tsx
Labels: design

#74 Style/칵테일 레시피 스켈레톤 작업#14
  package.json
  src/app/recipe/page.tsx
  src/domains/recipe/CocktailCard.tsx
  src/domains/recipe/details/DetailList.tsx
  src/domains/recipe/details/DetailMain.tsx
  src/domains/recipe/skeleton/SkeletonDetail.tsx
  src/domains/recipe/skeleton/SkeletonRecipe.tsx
  src/domains/shared/components/page-header/PageHeader.tsx
  src/shared/components/Input-box/Input.tsx
Labels: design

#75 [style] 스켈레톤 ui 작업
  src/app/recommend/loading.tsx
  src/app/recommend/page.tsx
  src/domains/recommend/components/ChatCocktailCard.tsx
  src/domains/recommend/components/ChatForm.tsx
  src/domains/recommend/components/SsuryChat.tsx
  src/shared/assets/images/recommend_bg.webp
Labels: design

#76 Style/recipe skeleton#14
  src/app/recipe/page.tsx
  src/domains/recipe/CocktailList.tsx
  src/domains/recipe/skeleton/SkeletonRecipe.tsx
Labels: design

#77 [feat] 챗봇 추천페이지 입력 폼 기능
  src/app/recommend/page.tsx
  src/domains/recipe/skeleton/SkeletonRecipe.tsx
  src/domains/recommend/components/ChatForm.tsx
  src/domains/recommend/components/ChatSection.tsx
  src/domains/recommend/components/MyChat.tsx
  src/shared/utills/handleTextareaSubmit.ts
  src/shared/utills/keyDown.ts
  src/shared/utills/textareaResize.ts
Labels: feat

#79 Style/community#18
  src/app/community/[id]/page.tsx
  src/app/community/write/page.tsx
  src/domains/community/components/postInfo/PostInfo.tsx
  src/domains/community/components/tag/CocktailTag.tsx
  src/domains/community/components/tag/Tag.tsx
  src/domains/community/components/tag/TagList.tsx
  src/domains/community/detail/CocktailTag.tsx
  src/domains/community/detail/DetailContent.tsx
  src/domains/community/main/PostCard.tsx
  src/domains/community/write/Category.tsx
  src/domains/community/write/CompleteBtn.tsx
  src/domains/community/write/FormTitle.tsx
  src/domains/community/write/WriteForm.tsx
  src/domains/community/write/cocktail-tag/TagModal.tsx
  src/domains/community/write/image-upload/DragandClick.tsx
  src/domains/community/write/image-upload/ImageSection.tsx
  src/domains/community/write/image-upload/UploadedImage.tsx
  src/domains/recipe/CocktailCard.tsx
  src/domains/shared/components/select-box/SelectBox.tsx
  src/domains/shared/components/star-bg/StarBg.tsx
  src/domains/shared/hook/useCloseOutside.tsx
  src/shared/assets/icons/add_24.svg
  src/shared/assets/icons/delete_24.svg
  src/shared/components/modal-pop/ModalLayout.tsx
  src/shared/components/spinner/Spinner.tsx
  src/shared/styles/_base.css
  src/shared/styles/_components.css
  src/shared/styles/_utilities.css
Labels: design

#81 [style, docs] 챗봇 로딩 컴포넌트 /페이지 안 컴포넌트 네이밍 변경
  src/domains/recommend/components/BotCocktailCard.tsx
  src/domains/recommend/components/BotMessage.tsx
  src/domains/recommend/components/BotOptions.tsx
  src/domains/recommend/components/ChatSection.tsx
  src/domains/recommend/components/MessageInput.tsx
  src/domains/recommend/components/TypingIndicator.tsx
  src/domains/recommend/components/UserMessage.tsx
  src/shared/assets/images/shaker.png
  src/shared/assets/ssury/ssury_happy.webp
  src/shared/styles/_utilities.css
Labels: design, chore

#83 [Fix]레시피 페이지 진입시 에러 해결
  src/app/recipe/page.tsx
  src/domains/recipe/CocktailCard.tsx
Labels: fix

#84 [fix, refactor] 스크롤 커스텀 및 토스트/로그인 로직 및 훅 분리
  src/app/design-system/page.tsx
  src/domains/login/components/LoginRedirectHandler.tsx
  src/domains/login/components/LogoutConfirm.tsx
  src/domains/login/hook/useAuthHooks.ts
  src/domains/recommend/components/BotMessage.tsx
  src/domains/recommend/components/ChatSection.tsx
  src/domains/recommend/components/TypingIndicator.tsx
  src/domains/shared/store/auth.ts
  src/shared/components/header/DropdownMenu.tsx
  src/shared/components/header/HeaderBtn.tsx
  src/shared/components/toast/CustomToastUtils.tsx
  src/shared/hook/useToast.tsx
  src/shared/styles/_base.css
Labels: fix, refactor

#86 [chore] env환경변수설정
  next.config.ts
  src/app/api/config/appConfig.ts
  src/app/mypage/my-setting/page.tsx
  src/app/mypage/mybar/page.tsx
  src/domains/recipe/CocktailCard.tsx
  src/domains/shared/store/auth.ts
Labels: chore

#91 [feat] 추천 챗봇 페이지 자동 스크롤 구현
  src/domains/login/components/WelcomeModal.tsx
  src/domains/recommend/components/ChatSection.tsx
  src/domains/recommend/components/bot/BotCocktailCard.tsx
  src/domains/recommend/components/bot/BotMessage.tsx
  src/domains/recommend/components/bot/BotOptions.tsx
  src/domains/recommend/components/bot/NewMessageAlert.tsx
  src/domains/recommend/components/bot/TypingIndicator.tsx
  src/domains/recommend/components/user/MessageInput.tsx
  src/domains/recommend/components/user/UserMessage.tsx
Labels: feat

#93 [chore]next.config파일 수정r#15
  next.config.ts
  src/app/design-system/page.tsx
  src/app/mypage/mybar/page.tsx
  src/app/recipe/page.tsx
  src/domains/community/main/CommunityFilter.tsx
  src/domains/community/write/Category.tsx
  src/domains/community/write/cocktail-tag/TagModal.tsx
  src/domains/community/write/image-upload/UploadedImage.tsx
  src/domains/recipe/CocktailCard.tsx
  src/domains/recipe/CocktailList.tsx
  src/domains/recipe/components/main/Accordion.tsx
  src/domains/recipe/details/DetailItem.tsx
  src/domains/recipe/details/DetailRecommendList.tsx
  src/domains/recommend/components/bot/BotCocktailCard.tsx
  src/shared/assets/images/dummy/exampleCocktail.png
  src/shared/assets/images/exampleCocktail.png
  src/shared/components/select-box/SelectBox.tsx
  src/shared/hook/useCloseOutside.tsx
Labels: chore
