Repository prgrms-web-devcourse-final-project/WEB5_6_HaeDokCoding_FE, pull requests merged in 2025-10, with the labels that each got.

#95 Feat/레시피 페이지 무한스크롤#15
  package.json
  src/app/design-system/page.tsx
  src/app/mypage/my-active/my-comment/page.tsx
  src/app/mypage/my-active/my-like/page.tsx
  src/app/mypage/my-active/my-post/page.tsx
  src/app/mypage/my-bar/loading.tsx
  src/app/mypage/my-bar/page.tsx
  src/app/mypage/page.tsx
  src/app/recipe/page.tsx
  src/domains/community/write/cocktail-tag/TagModal.tsx
  src/domains/recipe/CocktailList.tsx
  src/domains/recipe/components/details/BackBtn.tsx
  src/domains/recipe/components/main/Accordion.tsx
  src/domains/recipe/details/DetailItem.tsx
  src/domains/recipe/details/DetailMain.tsx
  src/domains/recipe/details/DetailRecipe.tsx
  src/domains/recipe/details/DetailRecommendList.tsx
  src/domains/recipe/details/DetailsHeader.tsx
  src/domains/recipe/main/CocktailFilter.tsx
  src/domains/recipe/main/CocktailList.tsx
  src/domains/recipe/main/Cocktails.tsx
  src/domains/recipe/types/types.ts
  src/domains/recipe/utills/labelTitle.ts
  src/domains/shared/components/cocktail-card/CocktailCard.tsx
  src/domains/shared/components/label/Label.tsx
  src/domains/shared/hook/useCloseOutside.tsx
  src/domains/shared/hook/useIntersectionObserver.ts
  src/domains/shared/hook/useMemoScroll.ts
  src/shared/assets/images/exampleCocktail.png
  src/shared/components/select-box/SelectBox.tsx
Labels: feat

#98 [feat] 챗봇 추천페이지 단계별 api 연동 1차 반영
  src/app/mypage/my-bar/page.tsx
  src/app/recommend/page.tsx
  src/domains/recipe/details/DetailItem.tsx
  src/domains/recommend/api/chat.ts
  src/domains/recommend/components/ChatList.tsx
  src/domains/recommend/components/ChatSection.tsx
  src/domains/recommend/components/bot/BotCocktailCard.tsx
  src/domains/recommend/components/bot/BotMessage.tsx
  src/domains/recommend/components/bot/BotOptions.tsx
  src/domains/recommend/components/bot/TypingIndicator.tsx
  src/domains/recommend/components/user/MessageInput.tsx
  src/domains/recommend/hook/useChatScroll.ts
  src/domains/recommend/types/recommend.ts
Labels: feat

#99 Feat/comment#22
  package-lock.json
  package.json
  src/app/community/[id]/loading.tsx
  src/app/community/[id]/page.tsx
  src/domains/community/api/fetchComment.ts
  src/domains/community/api/fetchPost.ts
  src/domains/community/api/fetchView.ts
  src/domains/community/components/post-info/PostInfo.tsx
  src/domains/community/components/textarea/AutoGrowingTextarea.tsx
  src/domains/community/detail/Comment.tsx
  src/domains/community/detail/DetailSkeleton.tsx
  src/domains/community/detail/EditDelete.tsx
  src/domains/community/hook/useComment.ts
  src/domains/community/hook/useCommentAnimation.ts
  src/domains/community/hook/useItemVirtualizer.ts
  src/domains/community/hook/usePrevious.ts
  src/domains/community/types/post.d.ts
  src/domains/recipe/components/details/RecipeComment.tsx
  src/domains/shared/components/comment/CommentHeader.tsx
  src/domains/shared/components/comment/CommentList.tsx
  src/domains/shared/components/comment/CommentTitle.tsx
  src/domains/shared/store/auth.ts
  src/shared/components/textarea-box/Textarea.tsx
  src/shared/hook/useInfiniteScrollObserver.ts
  src/shared/utills/intervalCall.ts
Labels: feat

#102 Feat/recommend list#96
  src/domains/recipe/components/details/BackBtn.tsx
  src/domains/recipe/details/DetailItem.tsx
  src/domains/recipe/details/DetailList.tsx
  src/domains/recipe/details/DetailRecipe.tsx
  src/domains/recipe/details/DetailRecommendList.tsx
  src/domains/recipe/details/hook/ozToMl.ts
  src/domains/recipe/details/hook/useGlass.tsx
  src/domains/recipe/types/types.ts
  src/domains/shared/components/abv-graph/AbvGraph.tsx
  src/domains/shared/components/cocktail-card/CocktailCard.tsx
Labels: feat

#103 [fix] 챗봇 추천 페이지 단계별 일 시 자동 scroll 이슈
  src/app/recommend/page.tsx
  src/domains/recommend/components/ChatList.tsx
  src/domains/recommend/components/ChatSection.tsx
  src/domains/recommend/components/bot/NewMessageAlert.tsx
  src/domains/recommend/components/user/MessageInput.tsx
  src/domains/recommend/hook/useChatScroll.ts
  src/domains/recommend/types/recommend.ts
Labels: fix

#107 [feat] 챗봇 추천페이지 로직 수정
  src/domains/recommend/components/ChatList.tsx
  src/domains/recommend/components/ChatSection.tsx
  src/domains/recommend/components/bot/BotCocktailCard.tsx
  src/domains/recommend/components/bot/BotMessage.tsx
  src/domains/recommend/components/bot/TypingIndicator.tsx
  src/domains/recommend/components/user/MessageInput.tsx
  src/domains/recommend/components/user/UserMessage.tsx
  src/domains/recommend/hook/useChatInit.ts
  src/domains/recommend/hook/useChatScroll.ts
  src/domains/recommend/hook/useSelectedOptions.ts
  src/domains/recommend/types/recommend.ts
  src/shared/styles/_utilities.css
Labels: fix, feat

#109 Feat/마이페이지 개인화#106
  src/app/mypage/my-active/my-comment/page.tsx
  src/app/mypage/my-active/my-like/page.tsx
  src/app/mypage/my-active/my-post/page.tsx
  src/app/mypage/my-alarm/page.tsx
  src/app/mypage/my-bar/page.tsx
  src/domains/mypage/api/fetchProfile.ts
  src/domains/mypage/components/Alarm.tsx
  src/domains/mypage/components/EditNickName.tsx
  src/domains/mypage/components/ToggleBtn.tsx
  src/domains/mypage/components/WithdrawModal.tsx
  src/domains/mypage/components/pages/my-active/MyComment.tsx
  src/domains/mypage/components/pages/my-active/MyLike.tsx
  src/domains/mypage/components/pages/my-active/MyPost.tsx
  src/domains/mypage/components/pages/my-alarm/MyAlarm.tsx
  src/domains/mypage/components/pages/my-bar/MyBar.tsx
  src/domains/mypage/hook/useProfileSsury.tsx
  src/domains/mypage/main/MyAbv.tsx
  src/domains/mypage/main/MyNav.tsx
  src/domains/mypage/main/MyProfile.tsx
  src/domains/mypage/main/MySetting.tsx
  src/domains/mypage/main/SsuryImage.tsx
  src/domains/shared/components/abv-graph/AbvGraph.tsx
  src/shared/components/Input-box/Input.tsx
Labels: feat

#111 Feat/칵테일 페이지 검색 및 정렬기능#22
  next.config.ts
  src/app/community/page.tsx
  src/app/login/page.tsx
  src/app/mypage/my-active/my-comment/page.tsx
  src/app/mypage/my-active/my-like/page.tsx
  src/app/mypage/my-active/my-post/page.tsx
  src/app/mypage/my-alarm/page.tsx
  src/app/mypage/my-bar/page.tsx
  src/app/recipe/page.tsx
  src/domains/recipe/api/CocktailSearch.tsx
  src/domains/recipe/api/RecipeFetch.tsx
  src/domains/recipe/components/details/BackBtn.tsx
  src/domains/recipe/components/main/Accordion.tsx
  src/domains/recipe/components/main/CocktailFilter.tsx
  src/domains/recipe/components/main/CocktailList.tsx
  src/domains/recipe/components/main/CocktailSearchBar.tsx
  src/domains/recipe/components/main/Cocktails.tsx
  src/domains/recipe/details/DetailItem.tsx
  src/domains/recipe/details/DetailRecipe.tsx
  src/domains/recipe/hook/ozToMl.ts
  src/domains/recipe/hook/useGlass.tsx
  src/domains/recipe/hook/useSearchControl.tsx
  src/domains/recipe/main/Cocktails.tsx
  src/domains/shared/components/keep/Keep.tsx
  src/domains/shared/hook/useMemoScroll.ts
  src/shared/components/Input-box/Input.tsx
  src/shared/components/select-box/SelectBox.tsx
Labels: feat
